services:
  pecera.MongoConfig:
    factory:
      class: ../../../../Contexts/shared/infrastructure/persistence/mongo/MongoConfigFactory
      method: 'createConfig'

  pecera.MongoClient:
    factory:
      class: ../../../../Contexts/shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['pecera', '@pecera.MongoConfig']

  # HEALTH
  Apps.pecera.controllers.health.GetStatusController:
    class: ../../controllers/health/GetStatusController
    arguments: []

  # AUTH
  Apps.pecera.controllers.Auth.LoginController:
    class: ../../controllers/Auth/LoginController
    arguments: ['@pecera.Auth.application.LoginUser']

  Apps.pecera.controllers.Auth.RegisterController:
    class: ../../controllers/Auth/RegisterController
    arguments: ['@pecera.Auth.application.RegisterUser']

  Apps.pecera.controllers.Auth.ValidateMailController:
    class: ../../controllers/Auth/ValidateMailController
    arguments: ['@pecera.Auth.application.ValidateMail']
